name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: pwd
    - run: ls
    - working-directory: Rust
      run: pwd
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
